### ISSUE TITLE
Nuevo problema en FIUBA

### ISSUE THREAD

**Issue by LucasDondo** [FdelMazo/yamerecibi#1]
Ya no estás vos. 😭

**P.D.1** ¡muchísimas gracias y felicitaciones Fede! ¡Nos dejaste un gran y lindo legado! 🤩🥳👏🏻
**P.D.2** 🇨🇴.
**P.D.3** ⭐⭐⭐.
**P.D.4** 🏆🏆🏆🏆.

**Comment by FdelMazo** [comment]
Jajaja muchas gracias por las palabras Lucas! :smile:
